################################################################################
# Kitty Configuration
#                                           https://sw.kovidgoyal.net/kitty/conf
# See above link for documentation of configuration options.
################################################################################


################################################################################
# Font
#                                    https://sw.kovidgoyal.net/kitty/conf/#fonts
################################################################################
font_size        15.0
font_family      JetBrainsMonoNL Nerd Font Mono


################################################################################
# Text cursor customization
#                https://sw.kovidgoyal.net/kitty/conf/#text-cursor-customization
################################################################################
cursor_trail       1
cursor_trail_decay 0.001 0.3


################################################################################
# Window layout
#                            https://sw.kovidgoyal.net/kitty/conf/#window-layout
################################################################################
window_padding_width 10


################################################################################
# Tab bar
#                                  https://sw.kovidgoyal.net/kitty/conf/#tab-bar
################################################################################
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted


################################################################################
# Color scheme
#                             https://sw.kovidgoyal.net/kitty/conf/#color-scheme
################################################################################
include dracula.conf

background_opacity 0.85
background_blur    10


################################################################################
# Advanced
#                                 https://sw.kovidgoyal.net/kitty/conf/#advanced
################################################################################
allow_remote_control socket-only
listen_on unix:/tmp/kitty-{kitty_pid}.sock
shell_integration no-title


################################################################################
# OS specific tweaks
#                       https://sw.kovidgoyal.net/kitty/conf/#os-specific-tweaks
################################################################################
hide_window_decorations            titlebar-only
macos_option_as_alt                yes
macos_quit_when_last_window_closed yes
macos_show_window_title_in         none
macos_titlebar_color               system


################################################################################
# Keyboard shortcuts
#                       https://sw.kovidgoyal.net/kitty/conf/#keyboard-shortcuts
################################################################################
map ctrl+l clear_terminal scrollback active
