# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  brew:lock:
    cmd: brew bundle dump --no-vscode --force --describe
    desc: Dump Brewfile

  brew:install:
    cmd: brew bundle check || brew bundle install
    desc: Install from Brewfile

  dracula:add:
    vars:
      REPO: "{{index .CLI_ARGS_LIST 0}}"
    cmd: git submodule add https://github.com/dracula/{{.REPO}}.git dracula/{{.REPO}}

  dracula:remove:
    vars:
      REPO: "{{index .CLI_ARGS_LIST 0}}"
    cmds:
      - git submodule deinit --force dracula/{{.REPO}}
      - git rm --force dracula/{{.REPO}}
      - rm -rf .git/modules/dracula/{{.REPO}}

  stow:install:
    cmd: stow --dotfiles .
    desc: Install dotfiles
