# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

git:
  overrideGpg: true
  pagers:
    - pager: delta --paging=never

gui:
  commitAuthorShortLength: 15

os:
  editPreset: nvim-remote

customCommands:
  - key: w
    context: localBranches
    prompts:
      - type: input
        title: New worktree branch name (branch is off of '{{.SelectedLocalBranch.Name}}')
        key: BranchName
    command: git wt {{.Form.BranchName}} {{.SelectedLocalBranch.Name}}
    description: New worktree
