# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

git:
  overrideGpg: true
  pagers:
    - pager: delta --paging=never

gui:
  commitAuthorShortLength: 15

os:
  editPreset: nvim-remote
